### ISSUE TITLE
Wrong Module Size for EGS 1.3.1 

### ISSUE THREAD

**Issue by jjdb210** [Adventium-underscore/TEC-Autosplitter#1]
flipped digits in code...

Line 206: 
`                else if(moduleSize == 86417072)`

Should be:
`		else if(moduleSize == 86147072)`

EGS 1.3.1 won't detect as a result.

**Comment by Adventium-underscore** [comment]
Oops, thanks for catching that. EGS is the only platform I can't test myself, so it's the easiest to miss something on. Fixed now, thank you.
