### ISSUE TITLE
Update for TEC Version 1.3.4

### ISSUE THREAD

**Issue by AshvekRVega** [Adventium-underscore/TEC-Autosplitter#4]
Splitter doesnt seem to be working after the most recent update to Version 1.3.4 on TEC. unsure why and the splitter just fails to start however windows event viewer does catch it and send a report, i could copy and paste that to see if its a game issue or not id requested

**Comment by Adventium-underscore** [comment]
The reason for the autosplitter failing to start would be that the offsets that are used need to be changed. Thanks for letting me know, I forgot to check if it needed updating.

**Comment by AshvekRVega** [comment]
you are very welcome!

**Comment by Adventium-underscore** [comment]
Autosplitter has been updated
