### ISSUE TITLE
Game update broke it again

### ISSUE THREAD

**Issue by AshvekRVega** [Adventium-underscore/TEC-Autosplitter#5]
autosplitter is broke for newest version of tetris effect connect. not starting again. i... dont quite know what broke it. i did see the dynamic thing in the description but i tried a run and it didnt autostart the timer like last time i put in an issue about it.

**Comment by Adventium-underscore** [comment]
I was pretty sure that was gonna happen. Will update tomorrow.

**Comment by Adventium-underscore** [comment]
Did it tonight instead.
